version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: healthapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kris
      POSTGRES_PASSWORD: kris
      POSTGRES_DB: healthappdb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
